function histograms = removeSpatialInformation(histograms)
% REMOVESPATIALINFORMATION From spatial to simple histogram
%   HISTOGRAM = REMOVESPATIALINFORMATION(HISTOGRAM) removes the
%   spatial information from the 2 x 2 spatial histogram HISTOGRAM.

histograms = ...
    histograms(1:4:end,:) + ...
    histograms(2:4:end,:) + ...
    histograms(3:4:end,:) + ...
    histograms(4:4:end,:) / 4 ;
